export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS'

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS';
export const SET_NEW_PASSWORD_FAILURE = 'SET_NEW_PASSWORD_FAILURE';

export const GET_ALL_POINTS_REQUEST = 'GET_ALL_POINTS_REQUEST';
export const GET_ALL_POINTS_SUCCESS = 'GET_ALL_POINTS_SUCCESS';
export const GET_ALL_POINTS_FAILURE = 'GET_ALL_POINTS_FAILURE';


export const POST_ACT_SUCCESS = 'POST_ACT_SUCCESS';
export const POST_ACT_FAILURE = 'POST_ACT_FAILURE';

export const GET_USERPOINTS_SUCCESS = 'GET_USERPOINTS_SUCCESS';
export const GET_USERPOINTS_FAILURE = 'GET_USERPOINTS_FAILURE';

export const GET_USERACTS_SUCCESS = 'GET_USERACTS_SUCCESS';
export const GET_USERACTS_FAILURE = 'GET_USERACTS_FAILURE';

export const GET_ALLACTS_REQUEST = 'GET_ALLACTS_REQUEST';
export const GET_ALLACTS_SUCCESS = 'GET_ALLACTS_SUCCESS';
export const GET_ALLACTS_FAILURE = 'GET_ALLACTS_FAILURE';

export const SET_WITNESS = 'SET_WITNESS';
export const SET_ENCOURAGEMENT = 'SET_ENCOURAGEMENT';
export const SET_KINDNESS = 'SET_KINDNESS';

export const ADD_TYPE_FILTER = 'ADD_TYPE_FILTER';
export const REMOVE_TYPE_FILTER = 'REMOVE_TYPE_FILTER';

