export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_ALL_POINTS_REQUEST = 'GET_ALL_POINTS_REQUEST';
export const GET_ALL_POINTS_SUCCESS = 'GET_ALL_POINTS_SUCCESS';
export const GET_ALL_POINTS_FAILURE = 'GET_ALL_POINTS_FAILURE';


export const POST_ACT_SUCCESS = 'POST_ACT_SUCCESS';
export const POST_ACT_FAILURE = 'POST_ACT_FAILURE';

export const GET_USERPOINTS_SUCCESS = 'GET_USERPOINTS_SUCCESS';
export const GET_USERPOINTS_FAILURE = 'GET_USERPOINTS_FAILURE';